### PR TITLE
update sbt_gather to report whole of genome overlap for each match

### PR DESCRIPTION
**Pull request by ctb**
from conversations with @brooksph 

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
From https://github.com/dib-lab/sourmash/pull/136#issuecomment-281586278, the text

```the recovered matches hit 0.0% of the query``` is problematic :)

**Comment by brooksph** [comment]
@ctb This should be 100%. I think it's reporting the fraction of the query (1.0 here) instead of the percent. 
# running sourmash subcommand: sbt_gather
loaded query: all.fna... (k=21, DNA)
query signature has max_hash: 1844674407370955
found: 1.00 0.31 NC_000853.1 Thermotoga maritima MSB8 chromosome, complete genome
found: 0.90 0.28 NC_011978.1 Thermotoga neapolitana DSM 4359, complete genome
found: 1.00 0.26 NC_002163.1 Campylobacter jejuni subsp. jejuni NCTC 11168 = ATCC 700819 chromosome, complete genome
found: 0.48 0.15 NC_009486.1 Thermotoga petrophila RKU-1, complete genome
found 4 matches total
the recovered matches hit 1.0% of the query

Composition:
1.00 NC_002163.1 Campylobacter jejuni subsp. jejuni NCTC 11168 = ATCC 700819 chromosome, complete genome
1.00 NC_000853.1 Thermotoga maritima MSB8 chromosome, complete genome
1.00 NC_011978.1 Thermotoga neapolitana DSM 4359, complete genome
1.00 NC_009486.1 Thermotoga petrophila RKU-1, complete genome

**Comment by ctb** [comment]
@brooksph could you dump a few test signature files on me that illustrate the good new behavior (vs the bad old behavior) so that I can put in a test?

a ~dozen .sig files would be ideal, some with overlapping variation due to strain foo.

**Comment by brooksph** [comment]
@ctb they're in /mnt/home/brooksph/dev/sigs with -k 11,21,31

**Comment by ctb** [comment]
On Sat, Feb 25, 2017 at 09:50:51AM -0800, Phillip Brooks wrote:
> @ctb they're in /mnt/home/brooksph/dev/sigs with -k 11,21,31

ok - looks like they were calculated with --scaled 10000, and I can
go to ../fasta/ to build a concatenated signature from the raw FASTAs,
yah?

**Comment by ctb** [comment]
This is ready for review & merge, I think @brooksph @luizirber

**Comment by brooksph** [comment]
yes, --scaled 10000 and the concatenated files are in /mnt/home/brooksph/dev/fasta/all.fna with raw files in /mnt/home/brooksph/dev/fasta/*fna.gz

**Comment by ctb** [comment]
ready for review & merge @luizirber @betatim

**Pull request merged**
