### PR TITLE
Support both JSON and YAML formats for loading

### PR DESCRIPTION
**Pull request by ctb**
Additions to #71. Merge after #72.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review (and maybe merge!)

**Comment by lgautier** [comment]
Looks good. I have 2 comments about possible additional checks added to the code but nothing that would prevent a merge.

**Comment by ctb** [comment]
ok - happy to address comments/questions now or after merge, let me know (or just go ahead and merge).

**Comment by lgautier** [comment]
Main purpose of the comments was to be read (and it is done). I actually don't know what happen to them after a merge (do they disappear or enter a frozen state) ? Fine to merge otherwise.

**Comment by ctb** [comment]
Huh, I don't see the comments on the source code & I didn't get any notifications - did you mean the ones on the issue, maybe?

I think comments on source code stick around attached to the PR until their context changes (which may be never).

**Comment by lgautier** [comment]
Looks I had to **submit** the review (and I did not).

**Comment by ctb** [comment]
On Sun, Jan 01, 2017 at 05:29:30PM -0800, Laurent Gautier wrote:
> Looks I had to **submit** the review (and I did not).

ahh! I see them now, thx.

**Comment by lgautier** [comment]
@ctb : I accidentally removed the commits in #74 that were merged in #71. Can you do the following: 
1- comment & reopen
2- merge (again)
(I hope this is possible - I'll look into cherry picking the commits otherwise)

**Comment by ctb** [comment]
Sure! See https://github.com/dib-lab/sourmash/pull/78

**Pull request merged**
