### PR TITLE
add a '--rna' option

### PR DESCRIPTION
**Pull request by ctb**
Per https://github.com/dib-lab/sourmash/issues/151 this adds `--rna` as a synonym for `--dna`.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
@taylorreiter a review would be appreciated, at your leisure :)

**Comment by ctb** [comment]
Ready for review and merge! (The red flagged coverage differential is not real, it's due to some outdated information.)

**Comment by luizirber** [comment]
`codecov/patch` is not required anymore (I still think it's a good idea to keep `codecov/project` as a required check)

**Comment by ctb** [comment]
bump!

**Pull request merged**
