### PR TITLE
re-add 'signature' as alias for 'sig'

### LINKED ISSUE #880: sourmash signature fails in 3.1.0, but sourmash sig works
`sourmash signature merge` fails but `sourmash sig merge` works!

```
(tmp_sgc) tereiter@bm1:~/github/ibd/sandbox/all_sgc_sigs$ sourmash signature merge
sourmash: error: argument cmd: invalid choice: 'signature' (choose from 'categorize', 'compare', 'compute', 'dump', 'gather', 'import_csv', 'index', 'info', 'migrate', 'multigather', 'plot', 'sbt_combine', 'search', 'watch', 'lca', 'sig', 'storage')
```
```
(tmp_sgc) tereiter@bm1:~/github/ibd/sandbox/all_sgc_sigs$ sourmash sig merge
usage:  merge [-h] [-q] [-o FILE] [--flatten] [-k K] [--protein]
              [--no-protein] [--dayhoff] [--no-dayhoff] [--hp] [--no-hp]
              [--dna] [--no-dna]
              signatures [signatures ...]
 merge: error: the following arguments are required: signatures
```

### PR DESCRIPTION
**Pull request by ctb**
Fixes #880 

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
ARGH python2.7 does not support the aliases keyword! Hmm.

**Comment by ctb** [comment]
ready for review @taylorreiter @luizirber

**Comment by luizirber** [comment]
Too bad it shows both `sig` and `signature` in the `sourmash --help` message, maybe keep just `signature` and leave `sig` as a shortcut (but not mentioned?)

**Comment by luizirber** [comment]
Also: release this as 3.2.1

**Comment by luizirber** [comment]
Ended up adding an `alias` mapping in https://github.com/dib-lab/sourmash/pull/881/commits/e07dc5e830d6b37bfc4a165bd930e802cd636ba7, what do you think @ctb?

**Comment by ctb** [comment]
I’d implemented almost exactly that at first, and then discovered aliases= option in python3, and after having to back that out because of python27 incompatibility I was broken in spirit and didn’t put the original fix back in. So I approve wholeheartedly :)

**Pull request merged**
