### PR TITLE
Seed when computing hashes now a parameter for all C-level

### PR DESCRIPTION
**Pull request by lgautier**
Initial changes to expose hashing seed used at C-level as a parameter (see issue #76).

If deemed reasonable this can be propagated up to command-line.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Is this ready to be reviewed @lgautier ?

**Comment by ctb** [comment]
On a quick skim, the only problem I see is that the seed code isn't executed by any tests, nor is the seed saved in any signature/estimator location. I'm happy to address both of those post-merge over in #91, where I'm mucking about with that stuff.

**Comment by lgautier** [comment]
It is in the sense that pull request is mostly consistent and self-sufficient. The only possible inconsistency is that until the seed is saved into JSON/YAML the consistency between save/load cycles can be broken, also this is not an issue for the casual user since the command line is not letting one play with the seed.

I am seeing the following missing:
- bubbling the seed up to the command line interface
- save the seed in the JSON / YAML (for the time it must be supported)
- read the seed from the JSON (assume default seed with a warning if missing seed ?)

I'd say review and merge now, than quickly add the save/read seed to/from JSON/YAML ASAP.

**Comment by ctb** [comment]
Agreed! I can do the add/save etc in #91.

**Comment by ctb** [comment]
LGTM.

**Comment by lgautier** [comment]
> On a quick skim, the only problem I see is that the seed code isn't executed by any tests, nor is the seed saved in any signature/estimator location. I'm happy to address both of those post-merge over in #91, where I'm mucking about with that stuff.

Pickling / unplicking should not be problem since this seed is a default type... but I realizing while writing this that seed is not stored at the Python level. I am happy to give an hand in #91 about this if needed.

**Pull request merged**
