### PR TITLE
[MRG] Document `sourmash.fig`usage and behavior

### LINKED ISSUE #220: sourmash compare output
Provide an option for the sourmash compare output, or an additional command that takes the sourmash compare matrix output as input, where the output reflects the clustering produced by sourmash plot. The output of this command would be another matrix, which ideally would be able to be exported as a csv.

### LINKED ISSUE #311: Sourmash plot - colour of the dendrogram?
Hey

I have a sourmash plot after running sourmash compare, and the dendrogram just looks like some random colours.  Just cycles through black, yellow, pink, blue, red, green.  The dendrogram higher up is just blue.

How do I change/control this?  The dendrogram in your tutorial looks much smarter

Cheers
Mick

### LINKED ISSUE #501: importing sourmash.fig
```
import sourmash

sourmash.fig.load_matrix_and_labels('mat')
```
gives the error: 'sourmash' has no attribute 'fig'.

However running:
```
import sourmash.fig
```

restores functionality. Should `sourmash.fig` be imported with `sourmash`?

### LINKED ISSUE #1023: Difficulty in matching dendrogram & heatmap names to filenames
Hi all - firstly, thanks for `sourmash`! I was going to implement my own minhash and was very happy to find `sourmash`.

When following the instructions on using `sourmash` (running `compute`, `compare` and `plot`), I end up with `.png` files of a heatmap and a dendrogram. However the labels of the files involved are almost unreadable (see attached, and that's when I'm zoomed in) and (in the dendrogram are truncated to identical suffixes).

Before going to look at the code to see if it's easy to do something about this, I'm wondering if the order of the filenames in the `.labels.txt` file will match the 0-based numbering in the heatmap labels? If so I can try harder to make out the numbers in the heatmap.

Thanks for any suggestions / help!

Screenshot from 2020-06-15 10-59-50
Screenshot from 2020-06-15 11-00-48

### PR DESCRIPTION
**Pull request by ctb**
Add a notebook showcasing `sourmash.fig` for matrix/dendrogram plotting, and link the notebook into the documentation. Provide code examples for customizing the dendrogram.

* view new notebook, [Building plots from `sourmash compare` output](https://github.com/dib-lab/sourmash/blob/add/compare_notebook/doc/plotting-compare.ipynb)
* [run notebook in binder, off of this branch](https://mybinder.org/v2/gh/dib-lab/sourmash/add/compare_notebook?filepath=doc%2Fplotting-compare.ipynb)

Note that the binder environment loads correctly and the paths are set up properly, but until the next conda release this notebook won't work. Not 100% sure how to deal with that but it does render on the documentation site properly ;).

Fixes #501
Fixes #220 
Fixes #1023 
Fixes #311

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review! @taylorreiter @bluegenes

**Comment by ctb** [comment]
anyone? Bueller? ...Bueller?

:)

**Comment by taylorreiter** [comment]
Should the binder work now? 

This cell:
```
f, reordered_labels, reordered_matrix = fig.plot_composite_matrix(matrix, labels)
```

Gives me:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-4d0f52de32a5> in <module>
----> 1 f, reordered_labels, reordered_matrix = fig.plot_composite_matrix(matrix, labels)

TypeError: cannot unpack non-iterable Figure object
```

**Comment by ctb** [comment]
On Wed, Jul 22, 2020 at 07:46:38AM -0700, Taylor Reiter wrote:
> Should the binder work now? 

alas, it will not, until this is merged into master and released.

**Comment by taylorreiter** [comment]
Then LGTM!

**Comment by ctb** [comment]
thanks!

**Pull request merged**
