### PR TITLE
[MRG] use tox for running tests locally

### PR DESCRIPTION
**Pull request by luizirber**
Benefits:

- Only need to install `tox`, and it takes care of installing all other deps.
- Isolate code and temp files, avoiding testing the code in the dir (instead of the installed code)

(This is a slim version of #680, skipping the `fix_lint` parts that change A LOT of code)

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed without a major version increment. Changing file formats also requires a major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
[This branch](https://github.com/dib-lab/sourmash/compare/build/tox_travis...checks) runs `black` and some other of the `pre-commit` formatters, and shows how it will look like. I'm not adding to this PR because... it is massive =]

**Comment by luizirber** [comment]
Changes up for discussion in this PR:
- I [updated docs](https://github.com/dib-lab/sourmash/pull/696/files#diff-a4eb66af9fff88f9861c2bbafa21eaa8d5e6f9bab730e0617af700b6e92e2602) to recommend `tox` as the ONLY dependency to be installed, including using it to set up a `dev` virtualenv. 
- `sourmash/` moved to `src/sourmash/`, which will break current opened PRs.
- `fix_lint` activated by default, using [`darker`](https://pypi.org/project/darker/) to incrementally updating code to use `black` for formatting.

What do you think, @ctb?

**Comment by ctb** [comment]
hmm, let me dig in and try a few merges. may take me a few days tho.

**Comment by ctb** [comment]
## reviewing tox part of things

I started out by creating a new conda environment with python3.8 in it, and running tox; got:

```
ERROR:  py39: InterpreterNotFound: python3.9
ERROR:   py38: InvocationError for command /Users/t/dev/sourmash.tox/.tox/py38/bin/python -m pip install --exists-action w '/Users/t/dev/sourmash.tox/.tox/.tmp/package/1/sourmash-4.0.0a4.dev2+g12c7da8.zip[test,storage]' (exited with code 2)
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:  docs: InterpreterNotFound: python3.7
```

(I think the py38 / InvocationError is just a network error, so that's ok; will try again later.)

I'm not a fan of having the default be that a user has to have python 3.7, 3.8, and 3.9 installed just to run basic tests, so I suggest making that clear; I'll revisit the docs with that in mind.

### `tox -e py38` fails in naive conda environment

did `pip install tox` and got this; 
not sure if it is expected:
```
python -m pytest --cov=. --cov-report term-missing --cov-report=xml
/Users/t/dev/sourmash.tox/.tox/py38/bin/python: No module named pytest
make: *** [coverage] Error 1
ERROR: InvocationError for command /usr/bin/make coverage (exited with code 2)
```

### `tox -e dev` doesn't work

this one is listed in the developer docs...?

```
% tox -e dev
ERROR: unknown environment 'dev'

```

**Comment by ctb** [comment]
as far as moving code under `src/sourmash` goes, thanks, I hate it, but that's just because I'm a conservative kinda guy and hate learning new things if I don't have to :). Let me see how much slower it makes running the tests - that's my only remaining concern.

**Comment by ctb** [comment]
(as far as breaking existing PRs... most of them are yours!)

**Comment by luizirber** [comment]
> ## reviewing tox part of things
> ```
> ERROR:  py39: InterpreterNotFound: python3.9
> ERROR:   py38: InvocationError for command /Users/t/dev/sourmash.tox/.tox/py38/bin/python -m pip install --exists-action w '/Users/t/dev/sourmash.tox/.tox/.tmp/package/1/sourmash-4.0.0a4.dev2+g12c7da8.zip[test,storage]' (exited with code 2)
> ERROR:  py37: InterpreterNotFound: python3.7
> ERROR:  docs: InterpreterNotFound: python3.7
> ```
> 
> (I think the py38 / InvocationError is just a network error, so that's ok; will try again later.)
>
> I'm not a fan of having the default be that a user has to have python 3.7, 3.8, and 3.9 installed just to run basic tests, so I suggest making that clear; I'll revisit the docs with that in mind.

Hmm, what version of tox are you running? I set up `tox.ini` to skip missing versions, it shouldn't be erroring with py39 and py37...

(is this running on this branch? or `latest`? Because `docs` should always be using 3.8, and I see it trying to use 3.7 :thinking:)

> ### `tox -e py38` fails in naive conda environment
> 
> did `pip install tox` and got this;
> not sure if it is expected:
> 
> ```
> python -m pytest --cov=. --cov-report term-missing --cov-report=xml
> /Users/t/dev/sourmash.tox/.tox/py38/bin/python: No module named pytest
> make: *** [coverage] Error 1
> ERROR: InvocationError for command /usr/bin/make coverage (exited with code 2)
> ```

It makes sense that running `pytest` directly will fail, because it is not installed. But this is the command that was executed inside `tox -e py38`, right?

This worked for me:
```
conda create -n tox_test python=3.8
conda activate tox_test
python -m pip install tox
python -m tox -e py38
```
(I used `python -m {pip,tox}` because I had them installed somewhere else, and my environment was not picking the conda-installed ones)

> ### `tox -e dev` doesn't work
> 
> this one is listed in the developer docs...?
> 
> ```
> % tox -e dev
> ERROR: unknown environment 'dev'
> ```

Hmm, I'm increasingly thinking that you're not in the `build/tox_travis` branch, or it is an older revision... `dev` is the last item in `tox.ini`, can you check if it is there?

**Comment by ctb** [comment]
On Thu, Dec 10, 2020 at 09:23:13AM -0800, Luiz Irber wrote:
> (is this running on this branch? or `latest`? Because `docs` should always be using 3.8, and I see it trying to use 3.7 :thinking:)

oh. sorry. I think you nailed it :). trying again!

**Comment by luizirber** [comment]
> as far as moving code under `src/sourmash` goes, thanks, I hate it, but that's just because I'm a conservative kinda guy and hate learning new things if I don't have to :). Let me see how much slower it makes running the tests - that's my only remaining concern.

I get that, and it is a big change, but there are [good reasons](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) to use the `src/` layout, especially to be sure we are testing/measuring coverage for the right files...

> (as far as breaking existing PRs... most of them are yours!)

Good, so it is up to me to fix them =]

**Review by ctb — APPROVED** [review]
Looks good overall, nice work!

I think it would be good to update the docs to point at `src/sourmash/` rather than `sourmash/`.

Also, is there any documentation for the `nix` stuff?

**Comment by luizirber** [comment]
> I think it would be good to update the docs to point at `src/sourmash/` rather than `sourmash/`.

Yup, I'll do that now.

> Also, is there any documentation for the `nix` stuff?

I'll add docs and CI for that, it's what I've been using for local dev in my laptop (setting up Rust, python and tox), but since I do most of my dev in the remote workstation it is not as well tested/organized yet.

**Comment by ctb** [comment]
On Tue, Dec 15, 2020 at 10:42:31AM -0800, Luiz Irber wrote:
> > Also, is there any documentation for the `nix` stuff?
> 
> I'll add docs and CI for that, it's what I've been using for local dev in my laptop (setting up Rust, python and tox), but since I do most of my dev in the remote workstation it is not as well tested/organized yet.

ok, no worries/no need to invest in that now, but might be good to have an
issue placeholder for this.

**Pull request merged**
