### PR TITLE
[MRG] Benchmarks using ASV

### PR DESCRIPTION
**Pull request by luizirber**
- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
- How do we make this operational?
- It saves data between runs, can we use the Travis cache to save it?
- Should we deploy a server to run it?

**Comment by betatim** [comment]
My guess would be that the load and type of instance you get on travis varies too much to give you good results from run to run -> you'd need some stable/dedicated machine. Once you have that, webhook to trigger it and store results there as well (instead of travis cache)?

**Comment by ctb** [comment]
On Mon, Jan 09, 2017 at 03:56:38PM -0800, Luiz Irber wrote:
> - Should we deploy a server to run it?

no please

**Comment by betatim** [comment]
I'd like to use this for my benchmarking in #103 what needs doing to get it merged?

**Comment by luizirber** [comment]
@betatim I think a benchmark for `add_protein`, and maybe cleaning up the config file (take out all the comments). For now we just run it locally, since it would require a specialized server for CI (we can try travis, but in other PR).

**Comment by luizirber** [comment]
ready for review and merge @betatim @ctb

**Pull request merged**
