### PR TITLE
LCA search warning if query has abundance

### PR DESCRIPTION
**Pull request by luizirber**
Decided to print a warning and disable abundance instead of throwing an error.

## Checklist

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
Ready for review and merge @ctb

**Comment by ctb** [comment]
hi @luizirber I think that I should actually change the code to remove this all together. Should we merge this for now, and then fix it properly in a day or two, or what?

**Comment by luizirber** [comment]
> Should we merge this for now, and then fix it properly in a day or two, or what?

a day or two works for me, I think we should keep the test but you can take over this branch and do the removal as you like.

**Comment by ctb** [comment]
@luizirber take a look.

**Pull request merged**
