### PR TITLE
[MRG] Make the sourmash crate library-only

### PR DESCRIPTION
**Pull request by luizirber**
The Rust crate takes more time to compile than necessary because there is a half-assed rust CLI implementation, but it is never really going to be the main CLI.

I was thinking about moving it to another crate, but preferably something that wouldn't conflict with the main CLI (that's why it's called `smrs` currently, for 'sourmash in rust', but that's very confusing because it looks too much like sourmash without vogals, but in the wrong order)

But mainly, moving it to another crate also keeps the sourmash crate firmly in the "library" field, and forces me to be more thinkful about library changes =P

Another benefit is building smaller scale experiments, but still grounded in sourmash the library (like the draff implementation, for example). Right now supported sketches are defined in an [enum](https://github.com/dib-lab/sourmash/blob/448be5d011def85aee8300f5f58f772a6fc77d6e/src/sketch/mod.rs#L13), which is fine for sourmash-as-an-application but not so good if someone wants to use sourmash in other contexts (because they need to modify the library, instead of implementing a Trait for their own sketches). I think it's also a clearer path for what to include in the sourmash library, just as we experiment on the Python side before sending features into the Rust side this PR does something similar with experimental Rust code (and avoid feature creep).

(More info about trait vs enum solutions: https://users.rust-lang.org/t/performance-implications-of-box-trait-vs-enum-delegation/11957/4)

This PR does the split of the `sourmash` crate into three in `crates/`:
- `sourmash`: the library, contains the C API exposed for Python
- `smrs`: a command line in Rust, with some basic functionality (index, search) but not much more for now
- `draff`: another CLI, for draff sigs.

I intend to move the draff parts into the `draff` crate, and make sure the library code is open enough to support defining sketches and indices outside the library (and still give access to all the features)

(none of this gets merged before `3.0.0`, of course)

## Checklist

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
cc @ctb

**Comment by ctb** [comment]
FWIW, I think discussing it an issue makes more sense than a PR, but I will mightily resist the sway of functioning code... :)

I think the split makes more sense to me when you bring draff into it. I think I am against calling the rust library sourmash, tho, because at some point it just all gets confusing.

And that's my major objection - at some point we're spending all our time juggling library versions and releases, which gets really confusing. Maybe a good rule of thumb is that the number of components we're maintaining in a project should be less than the number of core maintainers??

**Comment by luizirber** [comment]
> FWIW, I think discussing it an issue makes more sense than a PR, but I will mightily resist the sway of functioning code... :)

Darn it, I thought it was going to work! =]

> I think the split makes more sense to me when you bring draff into it. I think I am against calling the rust library sourmash, tho, because at some point it just all gets confusing.

Errm, that's... an issue. The sourmash crate is already registered in crates.io
https://crates.io/crates/sourmash
and I was planning to push a new version when 3.0 is released. Are you saying the Rust side should have another name?

Part of this PR is also isolating the rust library from Python bits. Rust and Python tests were mixed in `tests/`, there was `benchmarks/` for the Python `asv` benchmarks and `benches/` for the Rust `criterion` benchmarks, and `src/` only had Rust code, with the Python code living in `sourmash/`, which I would argue is all way more confusing (where should I check to find any of these pieces?). 
 
> And that's my major objection - at some point we're spending all our time juggling library versions and releases, which gets really confusing.

That's one reason to keep the rust library here, with the Python binding always depending on the newest version. But I don't think they should be the same version, especially because the Python/CLI is way more mature than the Rust library (and it will need a bunch of version bumps that will not influence Python/CLI). 

> Maybe a good rule of thumb is that the number of components we're maintaining in a project should be less than the number of core maintainers??

With this PR both `smrs` and `draff` are ready to be split off from the main sourmash repo. `smrs` is never going to be official, but parts of `draff` might come back (as PRs to the sourmash crate), but it is a good exercise on maintaining the sourmash crate open to be extended externally (and not only by changing the library). I'm suggesting this because then the project doesn't have to maintain it (and I don't mind maintaining it for my own nefarious purposes =P)

Suggested plan:
1) split off `smrs` and `draff`
2) keep only rust library in `sourmash`
3) Rename the rust library?
4) Document better the relation between the rust library and Python/main sourmash code.

**Comment by luizirber** [comment]
(`-1,991` lines, how's that for maintainability, huh? =P)

**Comment by luizirber** [comment]
I moved the Rust bits in README.md to the `src/core` dir, and added a comment about what lives in Python (CLI and Python API) and what goes in Rust (core functionality).

**Comment by ctb** [comment]
I think you've laid out a good rationale for this PR based on separation of concerns and flexibility for future experimentation. But I'm wary of the continuing increase in complexity caused by this, because it sharply reduces the number of people who can work on the entirety of sourmash (<waves hand>).

Can we take some time after this merge to let sourmash 3.x marinate for a bit without further large scale reorg?

**Pull request merged**
