### PR TITLE
Ignore .sig and .sbt files for repo language stats

### PR DESCRIPTION
**Pull request by standage**
How is this not bothering you?!?!

Screen Shot 2020-01-15 at 4 01 01 PM

Just kidding, it was an easy change, and should make the repo's language stats summary a bit less bonkers.

### CODE REVIEW

**Comment by luizirber** [comment]
> How is this not bothering you?!?!

**Comment by luizirber** [comment]
It does bother me to no end, thanks for finding the fix =]

**Comment by standage** [comment]
https://github.com/github/linguist

**Comment by standage** [comment]
You're welcome for (probably) the biggest jump in your repo's test coverage EVER! 😂😂😂

**Comment by luizirber** [comment]
> You're welcome for (probably) the biggest jump in your repo's test coverage EVER! joyjoyjoy

haha, need to wait for travis and gh actions to finish running =P

**Comment by standage** [comment]
> haha, need to wait for travis and gh actions to finish running =P

You're telling me that number might change when all of the CI builds are done? I better take a screenshot and savor it while it lasts...

Screen Shot 2020-01-15 at 4 19 28 PM

**Comment by luizirber** [comment]
I tested this locally and it was misidentifying `include/sourmash.h` as C++, so I also fixed that.

**Comment by luizirber** [comment]
Thanks @standage!

**Pull request merged**
