### PR TITLE
Track abundance

### PR DESCRIPTION
**Pull request by luizirber**
Replace the `set` for a `map`, and keep track of abundance for the minhash kmers.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

(Ideally, merge after #45 ...)

## TODO

- [x] Trigger tests both with abundance and without
- [x] (Or just merge both implementation? It does behave just like the original one...)

### CODE REVIEW

**Comment by ctb** [comment]
I don't understand why the files diff shows a bunch of stuff from sbt_search; did you start this branch from master?

**Comment by ctb** [comment]
This all works for me, and passes the sniff test.  Nice work!

**Comment by luizirber** [comment]
Yikes, this branch was started from `sbt_search`, but then I picked up the commits from master too, so it is a bit messy to review... See if it is better now.

**Comment by ctb** [comment]
I figured it out :).  It looks great!  But tests are needed.

**Comment by ctb** [comment]
Curious, what does this do in `test_estimators.py`?

```
def test_jaccard_1(track_abundance):
```

I see that the test is run twice, once with it `track_abundance=True` and once with `track_abundance=False`, but I don't know why or how :)

**Comment by ctb** [comment]
Oh, I see, conftest.py - https://github.com/dib-lab/sourmash/blob/56b547875408ca6bfe881335d1385cf5a92d3364/sourmash_lib/conftest.py

I'll just, err, document that shall I?

**Comment by luizirber** [comment]
That's a [parameterized fixture][0], it is a bit magical but works for testing both implementations...

[0]: http://doc.pytest.org/en/latest/fixture.html#parametrizing-fixtures

**Comment by luizirber** [comment]
I'll recheck this branch (because I moved tests to new files), but should mostly be good to go.

**Comment by luizirber** [comment]
I think this is good to go

**Pull request merged**
