### PR TITLE
[MRG] Update documentation in various ways.

### LINKED ISSUE #272: link phil's ASM poster into documentation somewhere
https://osf.io/mu4gk/

### LINKED ISSUE #336: add mash screen blog post to list of blog posts
https://genomeinformatics.github.io/mash-screen/

also, all the sourmash lca ones.

### PR DESCRIPTION
**Pull request by ctb**
* Adds citations and blogposts to `doc/more-info.rst` - fixes #336.
* Adds link to @brooksph [ASM poster](https://osf.io/mu4gk/) - fixes #272.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review! @taylorreiter @brooksph @luizirber

**Comment by brooksph** [comment]
Lgtm

**Comment by taylorreiter** [comment]
LGTM too!

**Comment by ctb** [comment]
OK for future reference you would need to actually approve a review, nice people :). I'll use admin privileges to merge for now.

**Pull request merged**
