### PR TITLE
Json sig

### PR DESCRIPTION
**Pull request by lgautier**
?! I am seeing this come back as unmerged. I am opening a pull request for better visibility...

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
make sure you are doing a 'git fetch' in your local repos, and also
a 'git pull origin master' into your own master branch'.  it's definitely
merged into master.

**Comment by ctb** [comment]
Ahh, this looks like test code separated out into a new file, plus a warning. Good stuff. Although note that Python 2 is now fully supported (in #78).

**Comment by lgautier** [comment]
All seem good to merge. Someone to check ?
I can't wait to close this branch. Sorry to all about the time wasted.

**Comment by ctb** [comment]
LGTM!

**Pull request merged**
