### PR TITLE
Add Dayhoff encoding of amino acids

### PR DESCRIPTION
**Pull request by olgabot**
The Dayhoff encoding of amino acids was created by [Margaret Oakley Dayhoff](https://en.wikipedia.org/wiki/Margaret_Oakley_Dayhoff), arguably the first bioinformatician, and uses a lossy encoding of amino acid sequences. I'm interested in adding this feature to compare sequences across large evolutionary distances without penalizing minor residue changes.

 | Amino acid    | Property              | Dayhoff |
 |---------------|-----------------------|---------|
 | C             | Sulfur polymerization | a       |
 | A, G, P, S, T | Small                 | b       |
 | D, E, N, Q    | Acid and amide        | c       |
 | H, K, R       | Basic                 | d       |
 | I, L, M, V    | Hydrophobic           | e       |
 | F, W, Y       | Aromatic              | f       |

Dayhoff table from
Peris, P., López, D., & Campos, M. (2008).
IgTM: An algorithm to predict transmembrane domains and topology in
proteins. BMC Bioinformatics, 9(1), 1029–11.
http://doi.org/10.1186/1471-2105-9-367

Original source:
Dayhoff M. O., Schwartz R. M., Orcutt B. C. (1978).
A model of evolutionary change in proteins,
in Atlas of Protein Sequence and Structure,
ed Dayhoff M. O., editor.
(Washington, DC: National Biomedical Research Foundation; ), 345–352.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

~Yes, I'll remove the irrelevant 10x barcode commits..~ -- rebased and force-pushed

### CODE REVIEW

**Comment by ctb** [comment]
yay!!

**Comment by luizirber** [comment]
@olgabot I'm also seeing this segfault under Linux, I think there is something awry in the `_dna_to_aa` function. I'll take a closer look.

(BTW, awesome PR!)

**Comment by luizirber** [comment]
@olgabot I sent a PR to your branch, https://github.com/czbiohub/sourmash/pull/3

It keeps the logic from the previous translation unchanged, and avoid adding the `xxN` codons to the original table. Dayhoff encoding should stay the same (but can you check again the change from `residue` to `codon`?)

**Comment by luizirber** [comment]
On the testing side, the current ones do a great job of checking if the correct metadata is being generated, but it doesn't check the hashes per se (meaning: they are not checking the dayhoff translation).

**Comment by luizirber** [comment]
> Sorry, I don't understand. Should the tests also check for equivalency on the hashes themselves?

You don't need to go all the way to check for the hashes (but we do that in some places...), but currently the dayhoff encoding is not being tested? See https://codecov.io/gh/dib-lab/sourmash/pull/689/diff?src=pr&el=tree#D4-190 for example.

**Comment by luizirber** [comment]
Thanks @olgabot, this is amazing! I'll cut a new release with all the merged PRs from this weekend.

**Pull request merged**
