### PR TITLE
[MRG] Debug and fix SBT search

### PR DESCRIPTION
**Pull request by ctb**
We have a persistent problem in that sourmash sbt search does not find everything it should. Containment analysis (sourmash gather) seems to work fine.

First task: figure out how to reproduce it quickly & easily.
- [x] add `utils/check-tree.py` to systematically search trees for their leaves

Second task: scour the codebase with flame and acid.

- [x] fix via a1210a1

Ref #244 and #454.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
It looks to my naive eye like the problem is due to use of `max` instead of `min` to calculate the highest possible Jaccard similarity below an internal tree node. If so, this is a really embarrassing brain fart on my part.

**Comment by ctb** [comment]
@luizirber your thoughts welcome ... might be ready for merging.

**Comment by luizirber** [comment]
I aggree with the changes, but trying to think how to support them on `2.0.0a6` without breaking existing DBs (or sourmash installation): probably need to keep `max_n_below` as a synonym for `min_n_below` in the metadata?

**Comment by ctb** [comment]
On Mon, Jun 04, 2018 at 01:26:34PM -0700, Luiz Irber wrote:
> I aggree with the changes, but trying to think how to support them on `2.0.0a6` without breaking existing DBs (or sourmash installation): probably need to keep `max_n_below` as a synonym for `min_n_below` in the metadata?

I think it _should_ break existing DBs. You can't use existing DBs for search
without getting this parameter set. No?

**Comment by luizirber** [comment]
I bumped the version to `2.0.0a7`.

On the DB side, two things:
- Create a new "old DBs" section on the docs, to keep track of where they are
- Create a `migrate` command (ou use `convert`?), and only load the latest DB version available (right now it tries to be clever and load any older version, which might take a long time depending on what needs to be set)

**Pull request merged**
