### PR TITLE
Use pickle to save LeafNodes

### PR DESCRIPTION
**Pull request by ctb**
Question for @luizirber - is there a reason not to use pickle for the internal nodes, too? I'm not sure it matters one way or another but thought I'd ask.

- [ ] Is it mergeable?
- [ ] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Hmm, another question - does pickle work across Python 2 and 3? Right now our saved SBTs work equally well with python2 and python3...

**Comment by betatim** [comment]
Can't find a reference but I am pretty sure that `pickle` comes with a "use across python versions at your own risk" type health warning.

**Comment by luizirber** [comment]
Yeah, I would avoid using `pickle` because not only it is Python-centric, but it also is `2` and `3` incompatible... It is OK for local dev, but I don't think we should be sharing it as the SBT default format.

**Comment by ctb** [comment]
Nope.

**Pull request closed without merging**
