### PR TITLE
Add Sequence Bloom Tree-based search into sourmash

### PR DESCRIPTION
**Pull request by ctb**
Makes use of @luizirber code from https://github.com/luizirber/2016-sbt-minhash to provid indexing and search subcommands.

Interesting question to ask: should we copy the SBT files into this repo? We could either have the SBT stuff be another project or we could develop it as part of sourmash until we have reason to split it off. Alternatively we could develop the SBT code as part of khmer (again, until we have reason to split).

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [ ] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [ ] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
The lazy loading hack (5a78330) really speeds things up @luizirber!

**Comment by ctb** [comment]
@luizirber I'd be interested in a review of sbt.py and sbtmh.py changes, and you might find them useful to merge back into the 2016-sbt-minhash repo, too.

**Comment by luizirber** [comment]
Instead of merging back the sbt stuff, what do you think about developing it here in sourmash? No point in keep things synchronized in two different places...

**Comment by ctb** [comment]
On Mon, Nov 28, 2016 at 03:38:11PM -0800, Luiz Irber wrote:
> Instead of merging back the sbt stuff, what do you think about developing it here in sourmash? No point in keep things synchronized in two different places...

Sure, if you don't see a clear use for it elsewhere.

However, the sbt and sbtmh changes should be specifically reviewed by
someone. Right now they're all mixed up with the other stuff (in particular,
I don't think sbt_gather should be merged into master).  Shall I split things
out for review?

**Comment by luizirber** [comment]
The review will happen here (eventually =P), no need to split things. I'll post a warning on the old repo pointing to sourmash (and sbt_gather isn't really part of the sbt/sbtmh codebase anyway).

**Comment by ctb** [comment]
ok

**Comment by luizirber** [comment]
Needs some tests for `categorize` and `search`, but I'm merging because we are putting too much stuff on this already!

**Pull request merged**
