### PR TITLE
[MRG] add `signature cat` and `signature split` commands to combine/split signature files

### PR DESCRIPTION
**Pull request by ctb**
This PR adds a `cat` and a `split` command to the sig submodule, to concatenate and split collections of signatures.  See [this discussion](https://github.com/dib-lab/sourmash/issues/999#issuecomment-646223645) for the original motivation.

## sourmash cat

```
% sourmash sig cat podar-ref/*.fa.sig -o out

== This is sourmash version 3.3.2.dev9+g462bc387. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

loaded 192 signatures total.
saved 192 signatures
```

## sourmash split

```
% sourmash sig split --outdir /tmp/foo podar-ref/1.fa.sig

== This is sourmash version 3.3.2.dev9+g462bc387. ==
== Please cite Brown and Irber (2016), doi:10.21105/joss.00027. ==

Creating --outdir /tmp/foo
writing sig to /tmp/foo/c55d50b7.k=21.scaled=1000.DNA.dup=0.1.fa.sig
writing sig to /tmp/foo/c11126d0.k=31.scaled=1000.DNA.dup=0.1.fa.sig
writing sig to /tmp/foo/e2d11fb6.k=51.scaled=1000.DNA.dup=0.1.fa.sig
loaded and split 3 signatures total.
```

- [x] can we include stdin in the argument list? (punted to #1049)
- [x] should we also add a sig split (or something) command to write out a bunch of md5sum-named files?
- [x] make split work on LCA and SBT databases too
- [x] tests
- [x] add to docs
- [x] add --traverse, too? (punted to #1048)

---

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
I think this is ready for initial review @bluegenes @taylorreiter @luizirber -- the code is a bit ugly, but the functionality is really nice and already useful!

**Comment by bluegenes** [comment]
Thinking about use cases for `sig cat` - most of the time, I'd like to use this when I already have some sigs for a file, and want to add a new ksize, scaled or alpha.  Would it be possible to pipe signatures from compute to `sig cat`? Or, better, could we add a `compute --append` or `compute --add` that adds (cats) signatures into an existing signature file?

**Comment by ctb** [comment]
piping is currently in a separate issue, #1049. that's not to say we couldn't address it here but it's a chunk of extra work that I might not get to soon :)

note that `compute --append` wouldn't be more efficient than 

```
sourmash compute ... -o new_sigs
sourmash cat old_sigs new_sigs -o combined_sigs
```
although note that the implementation supports specifying the output file as one of the input files --

```
# overwrite old_sigs with concatenated signatures w00t w00t
sourmash cat old_sigs new_sigs -o old_sigs
```
which I could add as a test...

**Comment by ctb** [comment]
added in 084879c3. so, once we get stdin working, you could do

```
sourmash compute ... -o - | sourmash sig cat old.sigs - -o old.sigs
```
which would meet your needs, I think?

**Comment by bluegenes** [comment]
hadn't seen your issue on this! yep, that would definitely fit. Would def be nice to avoid writing an intermediate file

**Comment by ctb** [comment]
thanks!

**Pull request merged**
