### PR TITLE
[MRG] Add --singleton option to lca summarize

### LINKED ISSUE #914: sourmash lca summarize should work differently on signatures calculated with --singleton
Right now, if `sourmash lca summarize` is run with a signature that was calculated using the `--singleton` flag, `lca summarize` does not output a result per sketch within the signature, and only outputs a single result that summarizes the entire signature. I think it would be helpful to have this either not be the default behavior, or add a flag for `--singleton` to output an `lca summarize` summary for each of the sketches in the signature (that match the k-size).

### PR DESCRIPTION
**Pull request by ctb**
Adds `--singleton` option to lca summarize, which summarizes matches based on each signature rather than merging the signatures.

Fixes #914. Also see discussion there, esp in [this comment](https://github.com/dib-lab/sourmash/issues/914#issuecomment-605457836)

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review! @luizirber @bluegenes @standage @taylorreiter :)

**Comment by ctb** [comment]
One question for @luizirber is whether we want to add a DeprecationWarning or something similar for command-line options, since we are changing behavior in 4.0?

**Comment by luizirber** [comment]
> One question for @luizirber is whether we want to add a DeprecationWarning or something similar for command-line options, since we are changing behavior in 4.0?

I think so, but will probably need some new incantation (since we can't put decorators in an argparse option?). Probably check if it was used/set, and emit the `DeprecationWarning`

**Comment by luizirber** [comment]
This PR is failing in Python 2.7: https://travis-ci.com/github/dib-lab/sourmash/jobs/319816285#L1079

**Pull request merged**
