### PR TITLE
[MRG] release notes for v2.0

### LINKED ISSUE #623: update changelog / release notes for 2.0
hey @luizirber I don't actually see that we have release notes or a changelog. ...shall we start the tradition at 2.0.0 and simply say "lots of things changed from 1.0 to 2.0", or do you think I should do a high level summary, or what?

here's what we do for khmer: https://khmer.readthedocs.io/en/v2.1.1/release-notes/release-2.1.html

### PR DESCRIPTION
**Pull request by ctb**
Fixes #623.

[See rendered release notes](https://github.com/dib-lab/sourmash/blob/add/release_notes/doc/release-notes/sourmash-2.0.md)

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Wondering if this should be part of #592, or maybe a new "actually release 2.0 now" PR?

**Comment by ctb** [comment]
Ready for review (but not merge).

**Comment by ctb** [comment]
Hey @luizirber I think this is the last one that needs your attention before I can work more on the release.

**Comment by luizirber** [comment]
I brought in two changes:
 - fix travis wheel build
 - remove tests and benchmarks from the published pypi package, as well as test data (per #600). The dev instructions were already failing (I noticed this in #554). But fixing the "run tests from installed package" will require more work (punt to a 2.x patch?)

**Pull request merged**
