### PR TITLE
[MRG] move tests from `test_lca` into `test_lca_functions`

### PR DESCRIPTION
**Pull request by ctb**
#1022 added a new test file, `test_lca_functions.py`. This PR moves non-command-line tests from `test_lca.py` into `test_lca_functions.py`, and also removes unused imports.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
@erikyoung85 could you review this PR when you have time?

* look at the changed files (under "Files changed" tab for the PR), make sure it looks like only the changes described in the PR are made
* check out the branch, makes sure the tests pass on your own machine
* maybe see if there's anything else in `test_lca.py` that should be moved b/c it's not a command line or high level API test (I'm pretty sure not, but a reviewer should double check :)
* if you have any other comments to make, make 'em :)

thanks!

**Comment by erikyoung85** [comment]
Hey Titus, I'm curious if there is any easy way to know if a function is a command-line test or not

**Comment by ctb** [comment]
> Hey Titus, I'm curious if there is any easy way to know if a function is a command-line test or not

if it uses the `runscript` or `run_sourmash`, it's a command line test; if it's just running Python code, it's not.

in this case there's a bunch of LCA_Database tests that I left in, so it's not a clean division into command-line and not, so maybe that part of the review would be silly. 🤷‍♂️

**Comment by ctb** [comment]
@erikyoung85 any comments? or does everything look ok?

**Comment by erikyoung85** [comment]
Looks good to me! So sorry for how long this took especially since I was away from Sourmash all of yesterday and missed your comment. I'm guessing I should leave a review?

**Comment by ctb** [comment]
thanks!

**Pull request merged**
