### PR TITLE
[MRG] add some R examples and documentation for matrices

### PR DESCRIPTION
**Pull request by ctb**
An R example for loading in the matrix format.

See [doc/other-languages.md](https://github.com/dib-lab/sourmash/blob/add/r_docs/doc/other-languages.md), as well as [ecoli-cmp.Rmd](https://github.com/dib-lab/sourmash/blob/add/r_docs/doc/_static/ecoli-cmp.Rmd).

Ref https://github.com/dib-lab/sourmash/pull/217#issuecomment-371974958 cc @taylorreiter 

Ultimately it might be nice to have this be its own binder repo, but for now some static docs would be good.

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by ctb** [comment]
Ready for review (and merge?) cc @taylorreiter

**Comment by ctb** [comment]
we could also include some of the R code to plot taxonomies with metacodeR or whatever @taylorreiter likes using.

**Comment by taylorreiter** [comment]
Yes! I'll add some code in for taxonomies. 

There's a couple other things I want to tweak as well, but I will tend to them soon!

**Comment by ctb** [comment]
thanks!

also: the perfect is the enemy of the good enough -- if you get a chance to
review and it's not too bad, I'd suggest merging and then punting more
stuff to a new issue.

**Comment by ctb** [comment]
thanks @taylorreiter !

**Pull request merged**
