### PR TITLE
Replacing C++ with Rust

### PR DESCRIPTION
**Pull request by luizirber**
This PR replaces the C++ parts of sourmash with Rust.

Tests are passing, but some optimization might be good (especially on avoiding too many calls/memory copies across the FFI layer).

Other branches/PRs depending on this one:
- #532 starts moving more of the Python implementation to Rust: signature loading and saving. This removes the dependency on `ijson`, but I decided to keep it separated from this PR because the Python signature loading/saving code is fine (but I needed it implemented in the [Rust side](https://github.com/luizirber/sourmash-rust/pull/2) for the [webassembly](https://github.com/luizirber/sourmash-rust/pull/3) parts).
- There is a nodegraph implementation in Rust, exposed to Python in the [rust_nodegraph](https://github.com/dib-lab/sourmash/compare/master...rust_nodegraph) branch. Still need to fix and test more before turning into the default, but would also mean optional dependency on khmer.

There are more details in https://github.com/luizirber/2018-python-rust (the poster presented at BOSC and SciPy 2018).

## Checklist

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
Turns out there is only one place that uses the common set returned by `intersection`: the test method =P
https://github.com/dib-lab/sourmash/pull/424/commits/ccc05ec80a46b27892e1dc5699978b50c4e0d892#diff-acb3fd27a7c58bb1a046d1a231f2d6cdR277

While we don't have anything depending on this behavior I suggest we add an `in_common` argument (defaulting to `False`) to avoid having to build and output the common set.
https://github.com/dib-lab/sourmash/pull/424/commits/ccc05ec80a46b27892e1dc5699978b50c4e0d892#diff-2032759ae736988ba55922787626efb5R281
(I still need to do the rust wrapping around the common set, that's why it is a weird mixed implementation for now)

**Comment by ctb** [comment]
sounds good - issue or PR or ??

**Comment by luizirber** [comment]
@ctb: covered the intersection changes in #453

**Comment by luizirber** [comment]
Path to merge this:
- [ ] #577 to update travis in this PR
- [ ] #471 to fix versioning
- [ ] Add the infor from README, LICENSE and Makefile from luizirber/sourmash-rust into the current ones
- [ ] Avoid duplicating more test data
- [ ] Add Rust coverage to codecov

PRs depending on this one:
- [ ] #532 replaces the signature saving/loading with the Rust version

NOTE: the Rust code has more things that are not being exposed to Python right now (like the Index impl based on #556), and the previously mentioned #532.

Most of the code that was the C++ layer is in [src/lib.rs](https://github.com/dib-lab/sourmash/blob/bda9993601ebee1bc6213118ff87f6ff5d8d0558/src/lib.rs)

Ready for review and comments @ctb

**Comment by luizirber** [comment]
Wheel building working for this branch. It builds two universal (python 2 and 3) wheels, for both MacOS and Linux.

Example: https://github.com/luizirber/sourmash/releases/tag/v2.0.0a15

(and... I think I can make Windows wheels work too? cibuildwheel is so cool.)

**Comment by ctb** [comment]
just to check, this is not going to be part of sourmash 2, is it?

**Comment by luizirber** [comment]
On 12/29, C. Titus Brown wrote:
>Would prefer rust code be activated as part of 3.0 dev.

There won't ever be dev/a35 again. NEVER.

> The rest sounds good ;)

Is this the 'disabled' (option 1) or 'other repo/submodule' (option 2)?
At this point I do prefer 1, but I can revert the code to be 2.
(and submodules are a bit of a pain)

**Comment by luizirber** [comment]
@ctb #593 is the Rust parts of this PR; this one now replaces the C++ bits and set up travis properly.

**Comment by luizirber** [comment]
Ready for review and merge @ctb

**Pull request merged**
