### PR TITLE
[WIP] Add --csv output to 'sourmash compare'

### LINKED ISSUE #167: Add --csv option to sourmash compare
Current output is a numpy matrix. CSV will enable easy import to other packages like pandas. Please include column headers in csv output.

### PR DESCRIPTION
**Pull request by ctb**
Fixes #167.

@taylorreiter @brooksph could one of you try this out and provide a small snippet of R code for reading in the resulting matrix? thx!

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by taylorreiter** [comment]
Is this the functionality you wanted in the snippet of R code? Or did you want a plot as well? 
```
# Read in data
sourmash_comp_matrix <- read.csv("tara_dummy_comp.csv")
# Label the rows
rownames(sourmash_comp_matrix) <- colnames(sourmash_comp_matrix)
# Check data
head(sourmash_comp_matrix)
```

**Comment by ctb** [comment]
The R code works, yes? And if you have a quick plot that'd be great but if it's
a lot of work no need.

**Comment by taylorreiter** [comment]
R code works. One would have to point R to their own compare matrix output file, and be in the working directory in which that file resides, but it works. 



For plotting:
```
read_and_plot_sourmash_csv<-function(sourmash_comp_csv_name){ 
  # Read in data
    sourmash_comp_matrix <- read.csv(sourmash_comp_csv_name)
  # Label the rows
    rownames(sourmash_comp_matrix) <- colnames(sourmash_comp_matrix)
  
  # format for plotting
    x  <- as.matrix(sourmash_comp_matrix)
    dd.row <- as.dendrogram(hclust(dist(x)))
    row.ord <- order.dendrogram(dd.row)

    dd.col <- as.dendrogram(hclust(dist(t(x))))
    col.ord <- order.dendrogram(dd.col)
  # Call packages and plot
  # modified from http://latticeextra.r-forge.r-project.org/#dendrogramGrob&theme=default
  library(lattice)
  library(latticeExtra)
    levelplot(x[row.ord, col.ord],
              aspect = "fill",
              scales = list(x = list(rot = 90)),
              colorkey = list(space = "left"),
              legend =
                list(right =
                       list(fun = dendrogramGrob,
                            args =
                              list(x = dd.col, ord = col.ord,
                                   side = "right",
                                   size = 5)),
                     top =
                       list(fun = dendrogramGrob,
                            args =
                              list(x = dd.row, ord = row.ord, 
                                   side = "top",
                                   size = 5))))
}

# Usage
read_and_plot_sourmash_csv("tara_dummy_comp.csv")
```

**Comment by ctb** [comment]
thank you @taylorreiter!

**Comment by taylorreiter** [comment]
@ctb I can write these as functions or as documentation. Everything is in base R except Rtsne

```
# cd ecoli_many_sigs
# 
# curl -O -L https://github.com/dib-lab/sourmash/raw/master/data/eschericia-sigs.tar.gz
# 
# tar xzf eschericia-sigs.tar.gz
# rm eschericia-sigs.tar.gz
# 
# sourmash compare --csv ecoli.comp.csv *sig



sourmash_comp_matrix <- read.csv("~/Desktop/ecoli_many_sigs/ecoli.comp.csv")

# Label the rows
rownames(sourmash_comp_matrix) <- colnames(sourmash_comp_matrix)

# Transform for plotting
sourmash_comp_matrix <- as.matrix(sourmash_comp_matrix)


# make an mds plot
    fit <- dist(sourmash_comp_matrix)
    fit <- cmdscale(fit)
    x <- fit[, 1]
    y <- fit[, 2]
    plot(fit[ , 1], fit[ , 2], xlab = "Dimension 1", ylab = "Dimesion 2")
    text(x, y, pos = 4, labels = row.names(fit))

# make a tsne plot

library(Rtsne)
tsne_model <- Rtsne(sourmash_comp_matrix, check_duplicates=FALSE, pca=TRUE, perplexity=5, theta=0.5, dims=2)
d_tsne = as.data.frame(tsne_model$Y) 
plot(d_tsne$V1, d_tsne$V2)

# unclustered heatmap
heatmap(sourmash_comp_matrix, Colv=F, scale='none')

# clustered heatmap
hc.rows <- hclust(dist(sourmash_comp_matrix))
hc.cols <- hclust(dist(t(sourmash_comp_matrix)))
heatmap(sourmash_comp_matrix[cutree(hc.rows,k=2)==1,], Colv=as.dendrogram(hc.cols), scale='none')
```

**Comment by ctb** [comment]
thank you!

**Pull request merged**
