### PR TITLE
[MRG] compute-optimized MinHash (for small scaled or large cardinalities)

### LINKED ISSUE #1010: Dealing with scaled=1
Sometimes we recommend `--scaled 1` for exploration, but that can be dangerous. Internally the MinHash sketch is implemented as a sorted vector. They are good when operating on already calculated MinHash sketches (comparing, search, gather), but not so much for `compute`.  Since `scaled=1` keeps all hashes, any time a new one is inserted it will potentially force the reallocation of the whole vector, and it is really easy to get stuck with a very long running time (even for small bacterial genomes).

Possible solution: "Frozen" MH. In Python there is usually a "frozen" variant for some structures (`set` and `dict` come to mind) that don't allow insertion/removal but are optimize for indexing/access. We could do something like that, and use frozen versions for `compare`, `search` and `gather`. The current implementation would pretty much be the frozen version, and for efficient insertion we can use a `BTreeSet` or `BTreeMap` (for abundances) in Rust. On the Rust side the API can use `.into_mut()` or other `Into`-like methods to go from one representation to the other.

### PR DESCRIPTION
**Pull request by luizirber**
As discussed in #1010, for small scaled values or datasets with large cardinality the current implementation starts spending too much time reallocating the internal vector used for keeping `mins` and `abundances`. This PR is a first try on creating a compute-optimized MinHash that solves that problem, using `BTree` structures in Rust (a `BTreeSet` for mins and a `BTreeMap` for abunds, but could use only a `BTreeMap` since the keys are the mins already).

Anecdotally, I used this to calculate signatures for some long reads samples from CAMI 2, and it took 15 minutes instead of 2+ days (and haven't finished when I stopped running) of the current method.

BUT! All the other operations (merge, similarity, etc) are SLOWER. Only insertion ends up being faster. That's why I'm calling it "compute-optimized", because in the other cases it's better to use the current one. (Pending: analysis of `gather`, which does rebuild the query minhash a lot...)

Fixes #1010

## TODO

- [x] Keep two MinHash impls, this one and the original (this PR is replacing the old one for now)
- [x] set up `proptest` using both impls, see if they give same results
- [x] use this one in `build_templates` for compute

## Checklist

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [ ] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
Issues to punt from this PR:
- The B-Tree impl is a copy-paste-fix from the Vec impl. There is opportunity for refactoring and sharing most of the methods.
- More opportunities for property testing, because both impl should return the same results.
- This PR defaults `compute` to use the B-Tree impl. Add a flag in the CLI to choose the Vec one? The Vec one is better in very limited cases (very small datasets), so I think we don't need the CLI flag.
- Another refactoring opportunity: Move `add_sequence` and `add_protein` to `SigsTrait`, with a default implementation. It only requires `ksize()` and `add_word()`, and would avoid replicating that logic in many places.

**Comment by luizirber** [comment]
This is ready for review @ctb @olgabot @bluegenes 

It is still missing coverage on the Rust side (since most of those methods end up not being exposed to Python at all), I'll set them up as more oracle-based property testing (which will also raise the Vec-based MinHash coverage)

**Comment by ctb** [comment]
Huh. Those are a lot of issues to punt from this PR :).

This doesn't touch the Python API or command-line interface. I'm not sure how to review it because of that! I'm fine with merging it, I guess?

**Comment by luizirber** [comment]
> Huh. Those are a lot of issues to punt from this PR :).

I wanted to avoid making it even more massive with a bunch of random changes... And the refactors are easier later, because they will have a baseline that already works.

(And the `add_sequence`/`add_protein` was more a reminder for something that I noticed while doing this, but it's an ortogonal PR to this one).

> This doesn't touch the Python API or command-line interface. I'm not sure how to review it because of that! I'm fine with merging it, I guess?

I think this is the relevant info: https://github.com/luizirber/sourmash_resources/blob/03ca7cea8df4640f83fcfa3359ce0be9ce0abab1/README.md#compute

Performance didn't change for a regular use case, and it improved a lot for small scaled or large cardinalities. The mem consumption can be lowered (by using only a `BTreeMap` instead of `BTreeSet`+`BTreeMap` in the abundance case), but that can come later (it doesn't change the public API).

I'll bring up the coverage and test more on the Rust side, and then merge. And probably cut `3.3.2` before Monday?

**Comment by ctb** [comment]
sounds good to me. There are a few PRs I'd like to make it into a release but I guess we can alway cut another one soon after :)

**Pull request merged**
