### PR TITLE
Improve sketching performance with lookup tables for complement and DNA validation

### PR DESCRIPTION
**Pull request by luizirber**
As discussed in #860 

## Checklist

- [x] Is it mergeable?
- [x] `make test` Did it pass the tests?
- [x] `make coverage` Is the new code covered?
- [x] Did it change the command-line interface? Only additions are allowed
  without a major version increment. Changing file formats also requires a
  major version number increment.
- [x] Was a spellchecker run on the source code and documentation after
  changes were made?

### CODE REVIEW

**Comment by luizirber** [comment]
lookup version is slightly faster, and has the additional benefit of supporting a larger alphabet if needed.

Still trying to figure out the `add_sequence/invalid kmers` benchmark, why is it worse in both cases...

subtract:
```
$ cargo bench -- add_sequence --baseline master        
   Compiling sourmash v0.3.0 (/home_hd/luizirber/work/sourmash-bio/sourmash/src/core)
    Finished bench [optimized] target(s) in 32.58s
     Running target/release/deps/compute-5a1e1fd812a12533
add_sequence/valid      time:   [4.4042 ms 4.4782 ms 4.6503 ms]                               
                        change: [-12.154% -8.6508% -4.5141%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking add_sequence/lowercase: Collecting 10 samples in estimated 5.2291 s (1155 iteratio                                                                                               add_sequence/lowercase
                        time:   [4.3619 ms 4.4018 ms 4.4826 ms]
                        change: [-11.646% -9.9575% -8.1125%] (p = 0.00 < 0.05)
                        Performance has improved.
Benchmarking add_sequence/invalid kmers: Collecting 10 samples in estimated 5.2348 s (880 itera                                                                                               add_sequence/invalid kmers                        
                        time:   [5.6185 ms 5.7279 ms 5.8837 ms]
                        change: [+3.5217% +5.3752% +7.5531%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking add_sequence/force with valid kmers: Collecting 10 samples in estimated 5.1183 s (                                                                                               add_sequence/force with valid kmers                        
                        time:   [4.4263 ms 4.5007 ms 4.5679 ms]
                        change: [-13.739% -12.297% -10.888%] (p = 0.00 < 0.05)
                        Performance has improved.
```


lookup:
```
$ cargo bench -- add_sequence --baseline master
    Finished bench [optimized] target(s) in 0.09s
     Running target/release/deps/compute-5a1e1fd812a12533
add_sequence/valid
                        time:   [4.3554 ms 4.4261 ms 4.4796 ms]                               
                        change: [-14.417% -12.688% -11.146%] (p = 0.00 < 0.05)
                        Performance has improved.
Benchmarking add_sequence/lowercase: Collecting 10 samples in estimated 5.1056 s (1155 iteratio                                                                                               add_sequence/lowercase
                        time:   [4.3143 ms 4.5334 ms 4.6899 ms]
                        change: [-12.680% -10.424% -7.6624%] (p = 0.00 < 0.05)
                        Performance has improved.
Benchmarking add_sequence/invalid kmers: Collecting 10 samples in estimated 5.2714 s (880 itera                                                                                               add_sequence/invalid kmers                        
                        time:   [5.4728 ms 5.7002 ms 6.2149 ms]
                        change: [+2.5725% +13.765% +25.773%] (p = 0.02 < 0.05)
                        Performance has regressed.
Benchmarking add_sequence/force with valid kmers: Collecting 10 samples in estimated 5.0325 s (                                                                                               add_sequence/force with valid kmers                        
                        time:   [4.2993 ms 4.3398 ms 4.3841 ms]
                        change: [-15.854% -14.608% -13.417%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) high mild
  1 (10.00%) high severe
```

**Comment by luizirber** [comment]
consistent improvements with the erroneous k-mer skipping:
```
$ cargo bench -- add_sequence --baseline master
    Finished bench [optimized] target(s) in 0.07s
     Running target/release/deps/compute-6014b35004fac473
add_sequence/valid
                        time:   [4.4084 ms 4.4755 ms 4.6094 ms]                               
                        change: [-13.011% -10.845% -8.3078%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
add_sequence/lowercase
                        time:   [4.5550 ms 4.5941 ms 4.6269 ms]                                   
                        change: [-9.3351% -8.1544% -6.9689%] (p = 0.00 < 0.05)
                        Performance has improved.
add_sequence/invalid kmers                                                                            
                        time:   [4.5537 ms 4.9158 ms 5.4124 ms]
                        change: [-15.451% -10.357% -4.5474%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) high mild
  1 (10.00%) high severe
add_sequence/force with valid kmers                                                                            
                        time:   [4.4980 ms 4.5158 ms 4.5342 ms]
                        change: [-12.521% -11.405% -10.374%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by luizirber** [comment]
Ready for review and merge @ctb

**Comment by kloetzl** [comment]
The tables do not support lower case letters. Is that an intended change? Also, I think there is a bug hidden in the k-mer skipping logic. I will try to fix that myself, this time. ☺

**Pull request merged**
